trigger:
  paths:
    include:
    - backend/*
  branches:
    include:
    - main

variables:
  wd_path: 'backend'

pool:
  vmImage: windows-latest

stages:
  - stage: build
    displayName: 'test and build application'
    jobs:
    - job: test
      displayName: 'lint and unit test'
      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '16.x'
        displayName: 'Install Node.js'
      - script: |
          cd $(wd_path)
          npm install
          cd ..
        displayName: 'npm install'
      - script: |
          cd $(wd_path)
          npm run test
        displayName: 'npm run test'
    - job: build
      displayName: 'build'
      dependsOn: test
      condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
      steps:
      - script: |
          cd $(wd_path)
          npm install
          cd ..
        displayName: 'npm install'
      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: '$(wd_path)/'
          includeRootFolder: false
          archiveType: 'zip'
          archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
          replaceExistingArchive: true
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Build.ArtifactStagingDirectory)'
          artifact: 'drop_server_dev'
          publishLocation: 'pipeline'
  - stage: deploy
    displayName: 'deploy application to Azure'
    dependsOn: build
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    jobs:
    - job: deploy
      displayName: deploy appliction to Azure
      steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: 'current'
          artifactName: 'drop_server_dev'
          targetPath: '$(Pipeline.Workspace)'

      # - task: AzureRmWebAppDeployment@4
      #   displayName: 'Deploy Azure App Service'
      #   retryCountOnTaskFailure: 3
      #   inputs:
      #     ConnectionType: 'AzureRM'
      #     azureSubscription: 'rg_xuefeng_connection'
      #     appType: 'webApp'
      #     WebAppName: 'onlineStorageWebAppBackendxx'
      #     packageForLinux: '$(Pipeline.Workspace)/**/*.zip'