name: test

trigger:
  branches:
    include:
      - master

variables:
  wd_path: 'backend'

pool:
  vmImage: ubuntu-latest

stages:
  - stage: build
    jobs:
    - job: test
      steps:
      - script: echo '123'